ievents {}

http {
  server {
    listen 80;

    location /app1/ {
      proxy_pass http://app1:3000/;
    }

    location = /app1 {
      return 301 /app1/;
    }

    location /app2/ {
      proxy_pass http://app2:3000/;
    }

    location = /app2 {
      return 301 /app2/;
    }
  }
}
